print('Boas vindas ao nosso glorioso jogo de MADLIB!')
substantivo = input('Digite um NOME: ')
adjetivo = input('Digite um ADJETIVO: ')
verbo = input('Digite um VERBO: ')
objeto = input('Digite um OBJETO: ')
profissao = input('Digite uma PROFISSÃO: ')
adjetivo2 = input('Digite outro ADJETIVO: ')
numero = input('Digite um NÚMERO: ')
animal = input('Digite um ANIMAL: ')
objeto2 = input('Digite outro OBJETO: ')
objeto3 = input('Digite mais um OBJETO: ')

print()
print('Título: "A Grande Aventura no Escritório de Tecnologia"')
print()
print('Um dia, o ' + substantivo + ' estava trabalhando em um projeto super ' + adjetivo + '. De repente, o computador começou a ' + verbo + ' sozinho! Sem pensar duas vezes, o ' + substantivo + ' pegou seu ' + objeto + ' e começou a digitar comandos como um ' + profissao +'.')
print('"Preciso consertar isso antes qe o sistema fique ' + adjetivo2 +'!" exclamou o' + substantivo +'. Depois de '+ numero + ' tentativas, finalmente o computador respondeu: "O problema foi causado por um ' + animal + ' que estava no sistema!')
print('Com isso, o problema foi resolvido, e o' + substantivo + ' ganhou o prêmio de ' + objeto2 + ' mais inovador do ano. Moral da história: sempre leve seu ' + objeto3 + ' para o escritório, porque nunca se sabe quando você vai precisar!')

